inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - '.internal_test_app/**/*'


Bundler/DuplicatedGem:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 185

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'blacklight-access_controls.gemspec'
    - 'lib/blacklight-access_controls.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
   - 'spec/**/*_spec.rb'
