on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['3.4.4', '3.3.8', '3.2.8']
        rails_version: ['8.0.1', '7.2.2.1', '7.1.5.1']

    runs-on: ubuntu-latest
    name: ruby ${{ matrix.ruby_version }} | rails ${{ matrix.rails_version }}
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-kamal --skip-solid --skip-coffee --skip-test --skip-assets"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: "latest"
          ruby-version: ${{ matrix.ruby_version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake ci
